// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Main$Rembrant = require("./Main.bs.js");
var Rembrandt$Rembrant = require("./Rembrandt.bs.js");

function update(model, action) {
  if (action.tag) {
    return model - action[0] | 0;
  } else {
    return model + action[0] | 0;
  }
}

Rembrandt$Rembrant.run((function (model, dispatch) {
        return Main$Rembrant.div(undefined, undefined, undefined, undefined, /* :: */[
                    Main$Rembrant.div(undefined, undefined, "height:100px;width:100px;", Js_primitive.some((function () {
                                Curry._1(dispatch, /* ADD */Block.__(0, [3]));
                                return "test test test";
                              })), /* :: */[
                          Main$Rembrant.text(String(model)),
                          /* [] */0
                        ], /* () */0),
                    /* [] */0
                  ], /* () */0);
      }), 42, update);

exports.update = update;
/*  Not a pure module */
