// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


var setAttributes = (
 function (attributes, element) {
	for (let i=0; i <attributes.length; i++) {
      element.setAttribute(attributes[i][0], attributes[i][1]);
   }
   return element;
 }
);

var replaceChild = (
        function(parent, newNode, oldNode) {
            return parent.replaceChild(newNode, oldNode);
        }
    );

var init = (
    function(id, element) {
      return document.getElementById(id).appendChild(element);
    }
  );

var createTextNode = (
    function(text) {
      return document.createTextNode(text);
    }
);

var removeChild = (
      function(parent, child) {
        return parent.removeChild(child);
      }
  );

var appendChild = (
   function (children, parent) {
      for (let i=0; i < children.length; i++) {
        if (Array.isArray(children[i])) {
          appendChild(children[i], parent);
        } else if (typeof children[i] !== 'number') {
          parent.appendChild(children[i]);
        }
      }
      return parent;
   }
  );

exports.setAttributes = setAttributes;
exports.replaceChild = replaceChild;
exports.init = init;
exports.createTextNode = createTextNode;
exports.removeChild = removeChild;
exports.appendChild = appendChild;
/* setAttributes Not a pure module */
