// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

var setAttributes = (
 function (attributes, element) {
	for (let i=0; i <attributes.length; i++) {
      element.setAttribute(attributes[i][0], attributes[i][1]);
   }
   return element;
 }
);

var replaceChild = (
        function(parent, newNode, oldNode) {
            return parent.replaceChild(newNode, oldNode);
        }
    );

var init = (
    function(id, element) {
      return document.getElementById(id).appendChild(element);
    }
  );

var update = (
    function(id, element) {
      var app = document.getElementById(id);
      return app.replaceChild(element, app.firstChild);
    }
  );

var createTextNode = (
    function(text) {
      return document.createTextNode(text);
    }
);

var removeChild = (
      function(parent, child) {
        return parent.removeChild(child);
      }
  );

var appendChild = (
   function (children, parent) {
      for (let i=0; i < children.length; i++) {
        if (Array.isArray(children[i])) {
          appendChild(children[i], parent);
        } else if (typeof children[i] !== 'number') {
          parent.appendChild(children[i]);
        }
      }
      return parent;
   }
  );

var addEventListener = (
    function(handler, eventName, parent) {
      return parent.addEventListener(eventName, handler);
    }
  );

function setHandlers(handlers, parent) {
  List.map((function (param) {
          var handler = param[1];
          if (handler !== undefined) {
            return Curry._3(addEventListener, handler, param[0], parent);
          } else {
            return parent;
          }
        }), handlers);
  return parent;
}

exports.setAttributes = setAttributes;
exports.replaceChild = replaceChild;
exports.init = init;
exports.update = update;
exports.createTextNode = createTextNode;
exports.removeChild = removeChild;
exports.appendChild = appendChild;
exports.addEventListener = addEventListener;
exports.setHandlers = setHandlers;
/* setAttributes Not a pure module */
