// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Dom$Rembrant = require("./Dom.bs.js");

function text(s) {
  return /* record */[
          /* name : TEXT */1,
          /* text */s,
          /* attributes : array */[],
          /* children : [] */0,
          /* null */false
        ];
}

function div($staropt$star, $staropt$star$1, children, _) {
  var id = $staropt$star !== undefined ? $staropt$star : "";
  var _class = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return /* record */[
          /* name : DIV */0,
          /* text */"",
          /* attributes : array */[
            /* tuple */[
              "id",
              id
            ],
            /* tuple */[
              "class",
              _class
            ]
          ],
          /* children */children,
          /* null */false
        ];
}

function render(node) {
  var match = node[/* name */0];
  if (match) {
    return Curry._1(Dom$Rembrant.createTextNode, node[/* text */1]);
  } else {
    return Curry._2(Dom$Rembrant.appendChild, List.map(render, node[/* children */3]), Curry._2(Dom$Rembrant.setAttributes, node[/* attributes */2], document.createElement("div")));
  }
}

function component(_, _$1) {
  return div("component", undefined, /* [] */0, /* () */0);
}

var jsx = div("1", "cls", /* :: */[
      div("2", "cls1", /* [] */0, /* () */0),
      /* :: */[
        div("2", "cls1", /* [] */0, /* () */0),
        /* :: */[
          div("2", "cls1", /* [] */0, /* () */0),
          /* :: */[
            div("2", "cls1", /* [] */0, /* () */0),
            /* :: */[
              div("2", "cls1", /* :: */[
                    component(/* () */0, /* [] */0),
                    /* :: */[
                      div("3", "cls1", /* [] */0, /* () */0),
                      /* :: */[
                        div("3", "cls1", /* [] */0, /* () */0),
                        /* :: */[
                          div("3", "cls1", /* [] */0, /* () */0),
                          /* :: */[
                            div("3", "cls1", /* :: */[
                                  /* record */[
                                    /* name : TEXT */1,
                                    /* text */"42",
                                    /* attributes : array */[],
                                    /* children : [] */0,
                                    /* null */false
                                  ],
                                  /* [] */0
                                ], /* () */0),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ], /* () */0),
              /* [] */0
            ]
          ]
        ]
      ]
    ], /* () */0);

var app = render(jsx);

exports.text = text;
exports.div = div;
exports.render = render;
exports.component = component;
exports.jsx = jsx;
exports.app = app;
/* jsx Not a pure module */
