// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Main$Rembrant = require("./Main.bs.js");

function dispatch(action, model, update) {
  return Curry._2(update, model, action);
}

function appRun(view, model, update) {
  var currentModel = /* record */[/* contents */model];
  var dispatchAction = function (action) {
    var action$1 = action;
    var model = currentModel;
    var update$1 = update;
    var updatedModel = Curry._2(update$1, model, action$1);
    currentModel[0] = updatedModel;
    return updatedModel;
  };
  return Main$Rembrant.render(Curry._2(view, model, dispatchAction));
}

exports.dispatch = dispatch;
exports.appRun = appRun;
/* Main-Rembrant Not a pure module */
