// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Dom$Rembrant = require("./Dom.bs.js");
var Main$Rembrant = require("./Main.bs.js");

function dispatch(action, model, update) {
  return Curry._2(update, model, action);
}

function run(view, model, update) {
  var root = document.createElement("div");
  var currentView = Main$Rembrant.div(undefined, undefined, undefined, undefined, /* [] */0, /* () */0);
  var dispatchAction = /* record */[/* contents */(function () {
        return false;
      })];
  var currentModel = /* record */[/* contents */model];
  dispatchAction[0] = (function (action) {
      var action$1 = action;
      var update$1 = update;
      currentModel[0] = Curry._2(update$1, currentModel[0], action$1);
      var updatedView = Curry._2(view, currentModel[0], dispatchAction[0]);
      Curry._2(Dom$Rembrant.update, "app", Main$Rembrant.render(updatedView));
      return true;
    });
  currentView = Curry._2(view, model, dispatchAction[0]);
  root = Curry._2(Dom$Rembrant.init, "app", Main$Rembrant.render(currentView));
  return /* () */0;
}

exports.dispatch = dispatch;
exports.run = run;
/* Dom-Rembrant Not a pure module */
