// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Dom$Rembrant = require("./Dom.bs.js");
var Main$Rembrant = require("./Main.bs.js");

function changed(node1, node2) {
  if (node1[/* name */0] !== node2[/* name */0]) {
    return true;
  } else {
    return node1[/* attributes */2] !== node2[/* attributes */2];
  }
}

function max(a, b) {
  var match = a > b;
  if (match) {
    return a;
  } else {
    return b;
  }
}

function updateElement(parent, newNode, oldNode, index) {
  if (oldNode[/* null */4]) {
    return Curry._2(Dom$Rembrant.appendChild, /* :: */[
                Main$Rembrant.render(newNode),
                /* [] */0
              ], parent);
  } else if (newNode[/* null */4]) {
    return Curry._2(Dom$Rembrant.removeChild, parent, List.nth(parent[/* childNodes */1], index));
  } else if (changed(newNode, oldNode)) {
    return Curry._3(Dom$Rembrant.replaceChild, parent, Main$Rembrant.render(newNode), Main$Rembrant.render(oldNode));
  } else {
    var newLength = List.length(newNode[/* children */3]);
    var oldLength = List.length(oldNode[/* children */3]);
    for(var i = max(newLength, oldLength); i >= 0; --i){
      updateElement(List.nth(parent[/* children */0], index), List.nth(newNode[/* children */3], i), List.nth(oldNode[/* children */3], i), i);
    }
    return parent;
  }
}

exports.changed = changed;
exports.max = max;
exports.updateElement = updateElement;
/* Dom-Rembrant Not a pure module */
